# coding: utf-8

"""
    Lidarr

    Lidarr API docs

    The version of the OpenAPI document: v2.1.7.4030
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, Optional
from lidarr.models.write_audio_tags_type import WriteAudioTagsType
from typing import Optional, Set
from typing_extensions import Self

class MetadataProviderConfigResource(BaseModel):
    """
    MetadataProviderConfigResource
    """ # noqa: E501
    id: Optional[StrictInt] = None
    metadata_source: Optional[StrictStr] = Field(default=None, alias="metadataSource")
    write_audio_tags: Optional[WriteAudioTagsType] = Field(default=None, alias="writeAudioTags")
    scrub_audio_tags: Optional[StrictBool] = Field(default=None, alias="scrubAudioTags")
    embed_cover_art: Optional[StrictBool] = Field(default=None, alias="embedCoverArt")
    __properties: ClassVar[List[str]] = ["id", "metadataSource", "writeAudioTags", "scrubAudioTags", "embedCoverArt"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MetadataProviderConfigResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if metadata_source (nullable) is None
        # and model_fields_set contains the field
        if self.metadata_source is None and "metadata_source" in self.model_fields_set:
            _dict['metadataSource'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MetadataProviderConfigResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "metadataSource": obj.get("metadataSource"),
            "writeAudioTags": obj.get("writeAudioTags"),
            "scrubAudioTags": obj.get("scrubAudioTags"),
            "embedCoverArt": obj.get("embedCoverArt")
        })
        return _obj


